# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100 #200
  tensorboard_logdir: tblog
  seed: 1
  user_dir: ???
  empty_cache_freq: 0

checkpoint:
  save_interval: 1
  keep_interval_updates: 1
  save_interval_updates: 2500
  best_checkpoint_metric: wer
  no_epoch_checkpoints: true


distributed_training:
  ddp_backend: c10d
  find_unused_parameters: false
  distributed_world_size: 7
  nprocs_per_node: 7

task:
  _name: MMS_LLaMA_training
  is_s2s: true
  data: ???
  label_dir: ???
  tokenizer_bpe_model: ???
  normalize: true  # must be consistent with pre-training
  labels: ["wrd"]
  single_target: true
  fine_tuning: true
  stack_order_audio: 4
  tokenizer_bpe_name: sentencepiece
  max_sample_size: 500
  min_sample_size: 10
  modalities: ["video", "audio"]
  image_aug: true
  pad_audio: true
  random_crop: false
  llm_path: ???
  noise_prob: ???
  noise_wav: ???


dataset:
  num_workers: 3
  max_tokens: 1000
  validate_after_updates: 0
  validate_interval: 1
  train_subset: train
  valid_subset: test

criterion:
  _name: decoder_only_language_modeling_loss
  report_accuracy: true
  label_smoothing: 0.1

optimization:
  max_epoch: 7
  max_update: 30000
  lr: [1e-4]
  sentence_avg: true
  update_freq: [1]
  clip_norm: 1.0

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: cosine
  warmup_updates: 500
  min_lr: 1e-5
  final_lr_scale: 0.05

model:
  _name: MMS-LLaMA
  ###### avhubert ########
  w2v_path: ???
  apply_mask: false
  mask_selection: static
  mask_length: 10
  mask_other: 0
  mask_prob: 0.75
  mask_channel_selection: static
  mask_channel_length: 64
  mask_channel_other: 0
  mask_channel_prob: 0.5
  layerdrop: 0.1
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
  feature_grad_mult: 1.0
  freeze_finetune_updates: 0
  ###### Llama ######
  target_modules : ???
  llama_embed_dim: 3072
  llm_path: meta-llama/Llama-3.2-3B
  lora_rank: 16
  lora_alpha: 32
  ###### AV Fusion ######
  whisper_embed_dim: 1024
  avhubert_embed_dim: 1024
  modality_fuse: concat #concat, add, cross-att
  ##### Q Former #######
  use_qformer: true
  queries_per_sec: 3
  qformer_layers: 2
  qformer_dim: 1024
  ##### Speech Rate Predictor #######
  use_sr_predictor: true


hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
          - task.label_dir
          - model.autoavsr_path
          - dataset.train_subset
          - dataset.valid_subset
          - criterion.wer_kenlm_model
          - criterion.wer_lexicon
          - model.conformer
  run:
    dir: ???
  sweep:
    dir: ???
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
